name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
          echo "EMAIL_SECRET=soubir0008@gmail.com" >> $GITHUB_ENV
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1" -OutFile "down.bat"
          cmd /c down.bat

      - name: Time Counter
        run: |
          # Ensure Python is installed
          choco install python -y
          python -m pip install --upgrade pip
          # Add any required Python packages below
          python -m pip install <package_name>  # Replace <package_name> with the necessary package
          python time.py  # Make sure 'time.py' is in the correct directory or provide the full path
